logger:
  log_level: 'DEBUG'
cors:
  cors_allow_methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
  cors_allow_origin: "*"
  cors_allow_credentials: "true"
  cors_allow_headers: "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With"
  cors_x_content_type_options: "nosniff"
  cors_x_frame_options: "SAMEORIGIN"
  cors_content_security_policy: "frame-ancestors 'self';"
http:
  server:
    http_server_port: '8088'
    http_server_write_timeout: 30
database:
  mongo:
    host: localhost
    port: 27017
    db: pkt_db